# Generated by Django 5.2.10 on 2026-01-28 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '✨ Créé'), ('update', '✏️ Modifié'), ('delete', '🗑️ Supprimé'), ('view', '👁️ Consulté'), ('login', '🔓 Connexion'), ('logout', '🔒 Déconnexion'), ('register', '📝 Inscription')], max_length=20)),
                ('content_type', models.CharField(help_text="Type d'objet modifié (Event, User, etc.)", max_length=100)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('object_name', models.CharField(help_text="Nom de l'objet modifié", max_length=255)),
                ('old_value', models.TextField(blank=True, help_text='Ancienne valeur')),
                ('new_value', models.TextField(blank=True, help_text='Nouvelle valeur')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Navigateur/Device')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Historique d'activité",
                'verbose_name_plural': "Historiques d'activités",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='dashboard_a_user_id_510456_idx'), models.Index(fields=['content_type', '-timestamp'], name='dashboard_a_content_e39eea_idx'), models.Index(fields=['-timestamp'], name='dashboard_a_timesta_77b0fd_idx')],
            },
        ),
    ]
