# Generated by Django 5.2.10 on 2026-01-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_user_bio_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('president', 'President'), ('vice_president', 'Vice President'), ('partnerships', 'Responsable Partenariats'), ('design', 'Responsable Design'), ('treasurer', 'Treasurer'), ('hr', 'Responsable RH'), ('media', 'Responsable Media'), ('events_manager', 'Responsable Événement'), ('member', 'Membre actif')], default='member', max_length=20),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('president', 'President'), ('vice_president', 'Vice President'), ('partnerships', 'Responsable Partenariats'), ('design', 'Responsable Design'), ('treasurer', 'Treasurer'), ('hr', 'Responsable RH'), ('media', 'Responsable Media'), ('events_manager', 'Responsable Événement'), ('member', 'Membre actif')], max_length=20)),
                ('feature', models.CharField(choices=[('create_event', 'Create Events'), ('edit_event', 'Edit Events'), ('delete_event', 'Delete Events'), ('create_announcement', 'Create Announcements'), ('edit_announcement', 'Edit Announcements'), ('delete_announcement', 'Delete Announcements'), ('create_project', 'Create Projects'), ('edit_project', 'Edit Projects'), ('delete_project', 'Delete Projects'), ('add_project_file', 'Add Files to Projects'), ('delete_project_file', 'Delete Project Files'), ('post_project_update', 'Post Project Updates'), ('access_admin', 'Access Admin Panel'), ('manage_users', 'Manage Users'), ('manage_roles', 'Manage User Roles')], max_length=50)),
                ('can_perform', models.BooleanField(default=False, help_text='Check to allow this role to perform this action')),
                ('description', models.TextField(blank=True, help_text='Explanation of what this permission allows')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Role Permissions',
                'ordering': ['role', 'feature'],
                'unique_together': {('role', 'feature')},
            },
        ),
    ]
