# Generated by Django 5.2.10 on 2026-02-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secondary_role',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('president', 'President'), ('vice_president', 'Vice President'), ('partnerships', 'Responsable Partenariats'), ('design', 'Responsable Design'), ('treasurer', 'Treasurer'), ('secretary', 'Secretaire'), ('hr', 'Responsable RH'), ('media', 'Responsable Media'), ('events_manager', 'Responsable Événement'), ('member', 'Membre actif')], max_length=20, null=True, verbose_name='Secondary Role (Optional)'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('president', 'President'), ('vice_president', 'Vice President'), ('partnerships', 'Responsable Partenariats'), ('design', 'Responsable Design'), ('treasurer', 'Treasurer'), ('secretary', 'Secretaire'), ('hr', 'Responsable RH'), ('media', 'Responsable Media'), ('events_manager', 'Responsable Événement'), ('member', 'Membre actif')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('president', 'President'), ('vice_president', 'Vice President'), ('partnerships', 'Responsable Partenariats'), ('design', 'Responsable Design'), ('treasurer', 'Treasurer'), ('secretary', 'Secretaire'), ('hr', 'Responsable RH'), ('media', 'Responsable Media'), ('events_manager', 'Responsable Événement'), ('member', 'Membre actif')], default='member', max_length=20, verbose_name='Primary Role'),
        ),
    ]
