# Generated by Django 5.2.10 on 2026-01-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('president', 'President'), ('vice_president', 'Vice President'), ('partnerships', 'Responsable Partenariats'), ('design', 'Responsable Design'), ('treasurer', 'Treasurer'), ('hr', 'Responsable RH'), ('media', 'Responsable Media'), ('events_manager', 'Responsable Événement'), ('member', 'Membre actif')], default='member', max_length=20),
        ),
    ]
